### ISSUE TITLE
Link: Simplification for Angular workaround possible?

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1024]
Is there a simplification for this?

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/991#discussion_r1193326875_

**Comment by nmerget** [comment]
How should we make this simpler? 

We have the same problem for every angular-component. Because angular will always add a custom `<db-xxx>` tag around the native HTML tag.

**Comment by nmerget** [comment]
@mfranzke can we close this?
