### ISSUE TITLE
Button Icons: Clarify declarations

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1041]
These declarations should even already get included via https://github.com/db-ui/mono/blob/main/packages/foundations/scss/icon/icons.scss#L11 – why do you need them (again)? And could you please leave a comment in case of e.g. an edge case?

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/603#discussion_r1194958054_

**Comment by nmerget** [comment]
I guess we had to use it at the beginning. I tested it again and couldn't find any issue, I think it is obsolete.
