### ISSUE TITLE
Tag: Clarify SCSS declarations

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1111]
@nmerget the selector `::before {` wouldn't work like this anyhow, so I've removed this in total as I don't get the use case.

https://github.com/db-ui/mono/pull/603/files/8d5b3354cf6447ac080f1a6ed716246f85b4580e#diff-dd9218f184f350c43ea2faa1eb9dedbd72a3f84d51ce92c9abce350e3e3b6f71R15-R19

same here:
https://github.com/db-ui/mono/pull/603/files#diff-dd9218f184f350c43ea2faa1eb9dedbd72a3f84d51ce92c9abce350e3e3b6f71R141-R144

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/603#discussion_r1221421044_

**Comment by nmerget** [comment]
> Most icons inside of a component should have the "element" color which is more like a highlight besides the standard font color.
> 
> I guess I missed the `&::before` but it should change the icon's color in front of the label.

It looks pretty strange with the element color... I asked @TOberpaul about his opinion. 
We should consider how to document if we use the element color for icons or not
