### ISSUE TITLE
Input: Make inner label an alternative and outside the default

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1123]
We've aligned that we will have the positioning the label on the outside of inputs the default. As we most likely would want to change the HTML order for that as well, we could make use of newer CSS syntax like e.g. `:has` to still set error colors on the label if this is needed:
```css
label:has(+ input:user-invalid) {
```

**Comment by nmerget** [comment]
We changed this behaviour with extra messages, so we don't need this issue anymore
