### ISSUE TITLE
Header: Default role added to the `header` tag

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1252]
The role `banner` is even already the default role on the `header` HTML tag, so we should clarify whether it has been added for a specific reason in the first place (it might have been needed in the past due to the lack of browser support):

https://github.com/db-ui/mono/blob/fb2602262ab6f98820425e6eab244ffc2d0ef5ed/packages/components/src/components/header/header.lite.tsx#L41

**Comment by nmerget** [comment]
Has been already removed: https://github.com/db-ui/mono/blob/main/packages/components/src/components/header/header.lite.tsx#L70
