### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1270]
Build `patternhub`. You'll recognize the following warning on console:

> Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at DBSelectFn (file:/// XXXXX /showcases/patternhub/components/src/dist/components/select/select.js:10:14)

**Comment by nmerget** [comment]
closed by https://github.com/db-ui/mono/issues/2251
