### ISSUE TITLE
Evaluate Prettier Cache usage

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1275]
We should evaluate to use prettiers cache usage – probably this is not relevant for staged files, but more or less in case you're prettifying a whole codebase, but you'll never know …

https://prettier.io/blog/2022/06/14/2.7.0.html

**Comment by nmerget** [comment]
This is an edge case because we are using `lintstaged`. The research/implementation for this may take longer then waiting for our computers to prettify the complete codebase...
