### ISSUE TITLE
Button: variant text with icon not aligned correctly

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#1350]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

E.g. <DBButton icon="delete" variant="text" onClick={() => {}}></DBButton> (React) – Icon is not correctly aligned

### Expected Behaviour

align icons vertically and horizontally centered

### Screenshots

![Bildschirmfoto 2023-07-31 um 14 27 30](https://github.com/db-ui/mono/assets/2963522/cc81e7f8-6d68-4fb7-9dc5-753f72416356)
![Bildschirmfoto 2023-07-31 um 14 27 36](https://github.com/db-ui/mono/assets/2963522/4ccf0bfb-c70d-464c-842a-8f6eae63810f)

### Browser version

Chrome

**Comment by nmerget** [comment]
The buttons should be square without any text, I added this in july: https://github.com/db-ui/mono/blob/main/packages/components/src/components/button/button.scss#L27

Is this still a problem in the current version?

**Comment by annsch** [comment]
no, it's squared now :)
