### ISSUE TITLE
unravel HTML attributes and SCSS placeholders/mixins contents

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1435]
Currently if someone wants to e.g. `@extend %db-ui-functional;` they would need to `@use '@db-ui/foundations/build/scss/tonality' as *;` – but this actually brings all the included CSS Selectors directly rendered into the output.

So we need to unravel HTML attributes and SCSS placeholder declarations and clearly document both of these endpoints for the different ways of consuming our library.

**Comment by nmerget** [comment]
I guess there is something wrong.

`@use '@db-ui/foundations/build/scss/variables' as *;` are only variables, and you don't need them for to extend `@extend %db-ui-functional;`

**Comment by mfranzke** [comment]
> I guess there is something wrong.
> 
> `@use '@db-ui/foundations/build/scss/variables' as *;` are only variables, and you don't need them for to extend `@extend %db-ui-functional;`

sorry, my bad – this is about `@use '@db-ui/foundations/build/scss/tonality' as *;`, I've even also corrected it within the description.

**Comment by nmerget** [comment]
We solved this already by adding `index.scss` files :)
