### ISSUE TITLE
Automate playwright Trace-Viewer

### ISSUE THREAD

**Issue by nmerget** [db-ui/mono#1452]
It would be cool to use https://trace.playwright.dev/ directly from a branch with failed tests.

We could enable this feature if we use another branch (similar to gh-pages), where we push failed trace.zip files for branches and print a link to the cicd summary with the correct path to the [trace viewer](https://playwright.dev/docs/trace-viewer#viewing-remote-traces).

Moreover we need to clean this branch like we did it with the gh-pages

**Comment by mfranzke** [comment]
you've closed this as "completed". Is it actually implemented ?

**Comment by nmerget** [comment]
It's a nice idea, but too much work for something we don't use much.
