### ISSUE TITLE
Remove `@csstools/normalize.css` from foundations

### ISSUE THREAD

**Issue by nmerget** [db-ui/mono#1494]
- We have a dependency for foundations that [normalizes css](https://github.com/db-ui/mono/blob/main/packages/foundations/package.json#L31) but a lot of those normalizes are overwritten later
- We should remove the dependency and check which of the normalizes matters for us and which ones we should adapt with our own variables (tonality etc.)

**Comment by mfranzke** [comment]
The beauty of including this as a dependency would be to even also get updates on case that new solutions or requirements for standard browser styling enhancements would need to be made.
But on the other hand we might even also enable this by watching for any new releases for this package as well.

**Comment by nmerget** [comment]
If we want to use it, we could include https://github.com/csstools/postcss-normalize.

This would give us the updates but would remove the dependency from our package.json.

But I think we just need 2-3 selectors of the normalize.css because a lot of the others needs our own spacings etc.
