### ISSUE TITLE
Evaluate whether we need some SVG fixture within our pipeline

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1500]
At the moment this is a manual process to fix the contents of the SVGs themselves. This might get solves when those getting exported, so it's probably good to open a follow up task.

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1490#discussion_r1308350675_

**Comment by nmerget** [comment]
We can close this right?

We do it for the solid & inverted icons inside the `tmp` directory and we get the correct icons in the future
