### ISSUE TITLE
Select: missing key problem logged

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1531]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Build `patternhub`. You'll recognize the following warning on console:
> Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at DBSelectFn (showcases/patternhub/components/src/dist/components/select/select.js:11:14)

### Expected Behaviour

This warning wouldn't get logged.

### Browser version

None

**Comment by nmerget** [comment]
It's the same for https://github.com/db-ui/mono/issues/1270 right?
