### ISSUE TITLE
question on `default-assets` within input

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1561]
Why do we need the `default-assets` here?

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1554#discussion_r1324498688_

**Comment by nmerget** [comment]
We should handle this correctly, the perfect solution would be to have an icon button for this with an absolute positioning, clearing the input. Maybe we can "fake" it by hiding the search-cancel icon but using the event from it.
