### ISSUE TITLE
Tooltip Dev Research: Review

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1589]
## General aspects
- A wrapping tag wouldn't be possible to get connected via [aria-describedby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) to the element that the tooltip gets displayed for, compare to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role
I assume that it would only act as a wrapper and the contents of the `title`-Attribute would get inserted into the DOM as well as an element and than get connected via that attribute, isn't it ?
- We should even also assess on the future solution for positioning: [CSS Anchor positioning](https://developer.chrome.com/blog/tether-elements-to-each-other-with-css-anchor-positioning/)

## Specific remarks

              > There are two ways to use a tooltip:
> 1. As wrapping tag `<tooltip content="xyz"><button>Test</button></tooltip>`
> 2. As property `<button tooltip/title="xyz">Test</button>`

why not provide both possibilities? The latter would be restricted not to be able to include an arrow.

> Could be hard to use default :hover or :focus

`:focus-within` as well as `:hover` would still work on the wrapper tag.

> We could use behaviour to enable different states like hover or clicked etc.

I agree with the comments on https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role that the tooltip wouldn't be interactive, that for I don't see the need for a `clicked` state. Or am I either misunderstanding something here or is it a requirement?

> By providing and `open` state we could let the user handle if the tooltip should be shown

Could you please further elaborate on this aspect? e.g. do you mean the developer or the user of the website? And why/how should the tooltip to be shown get handled?

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1588#discussion_r1329777762_

**Comment by nmerget** [comment]
In general look at [IBM](https://react.carbondesignsystem.com/?path=/docs/components-tooltip--overview), I suggest this as inspiration.

- They add a `div` as wrapper with `children` (in the example a `button`) and a `span` below the children.
During `onMount` we could get the `id` of the children and use it for `aria-describedby`.
Furthermore, the advantage of having a `span` as the tooltip: It would be hidden for the user before he hovers over the wrapping tag, but it would be visible to the DOM, which is nice for screenreaders. 
Some solutions add the tooltip via JS (adding a new DOM node) which I wouldn't recommend.
- Why should we use a polyfill here? We can use normal `position:absolute` for the default tooltip positions. Only a dynamic positioning would only work with JS, but that could be an improvement in the future.


> why not provide both possibilities? The latter would be restricted not to be able to include an arrow.

We should use a wrapping tag similar to IBM and a [title fallback](https://stackoverflow.com/questions/2011142/how-to-change-the-style-of-the-title-attribute-inside-an-anchor-tag).

^-- I wrote it like this. We should use both. And yes for `title` it could be hard/impossible to get an arrow.

> :focus-within as well as :hover would still work on the wrapper tag.

Yes right. We could handle it like this `.db-tooltip{ :has(> :hover){ & > span{visibility:visible}}}`

> clicked state & `open`

Good point. I think some DSs used the tooltip like a popover. Maybe we should create a popover component which acts the same like the tooltip, but you can use `hover` and `click`/`open` to handle the popover. The tooltip would then just use the popover component with the limits to pass only a string as content. And the stuff with the arrow and `title`.

**Comment by nmerget** [comment]
Our first attempt will be to include the tooltip into the component similar to the `badge`.

Example given:

````
<button class="db-button" id="button1">
Test
<span class="db-tooltip" role="tooltip" aria-describedby="button1">tooltip</span>
</button>
````
