### ISSUE TITLE
Icon mixin: why not have the solid/outline differentiation as a parameter

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1657]
why not have the solid/outline differentiation as a setting still as a parameter of the `icon()` mixin?

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1656#discussion_r1348452612_

**Comment by nmerget** [comment]
We could add it to `@mixin icon` function as well, but it should be its own `mixin`, too.
If there is some use-case where you just want to change the font-family it should be possible with `data-icon="xx"` without the need of the  `@mixin icon`.
