### ISSUE TITLE
Popover simplification

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1709]
Maybe the selector could get reduced to the following:
```suggestion
:has(.db-tooltip):hover {
```

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1659#discussion_r1366506404_

**Comment by nmerget** [comment]
Nope... This is the angular workaround, and sadly we need it :(

**Comment by mfranzke** [comment]
> Nope... This is the angular workaround, and sadly we need it :(

But why would `:has(.db-tooltip):hover` not select the same elements as the following one (in our implementation structure)?
```css
:has(> db-tooltip > .db-tooltip):hover,
:has(> dbtooltip > .db-tooltip):hover,
:has(> .db-tooltip):hover
```

**Comment by nmerget** [comment]
Popover completely changed, we can close this
