### ISSUE TITLE
popover: clarify `gap` property

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1711]
Let's align on this attribute and why we need to set it this way statically.

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1659#discussion_r1366512396_

**Comment by nmerget** [comment]
When I created the component we discussed with UX that we only provide the tooltip with the arrow. So I set the gap statically.
I saw that the specifications changed again. If this isn't the case anymore we might want to update this.
So we should force it when "withArrow" is set and let the gap optional for the "basic" variant.

**Comment by nmerget** [comment]
outdated
