### ISSUE TITLE
docs: how to document / integrate code parts

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1723]
Those variables still seem to constantly change – I'm how we could provide those overviews fail-safe regarding updates, like e.g. not including any values in here but only generating and visualizing them out of the code directly.

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1629#discussion_r1369692994_

**Comment by nmerget** [comment]
This is another problem we need to discuss with UX.
There should be a fixed range between 3xs and 3xl for every token, so we could reduce the complexity and write down the range.
But anyway, those variables have been the same since the beginning, so I don't know why you are concerned

**Comment by mfranzke** [comment]
> This is another problem we need to discuss with UX. There should be a fixed range between 3xs and 3xl for every token, so we could reduce the complexity and write down the range. But anyway, those variables have been the same since the beginning, so I don't know why you are concerned

It's mainly about that the consistency that you're suggesting (and that I would totally support) doesn't seem to be a given. So any code that we write or design tokens that we provide should better be generated out of the code than manually maintained in `.md` files besides necessary code changes (paradigms of "single source of truth" as well as "automate everything").

**Comment by nmerget** [comment]
The range will be the same for all tokens `3xs-3xl` there won't be any change for this system in the future. So we can close this

**Comment by mfranzke** [comment]
Furthermore we've ensured that the output is generated out of a JSON configuration.
