### ISSUE TITLE
docs: include CSS code next to HTML for general styling examples

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1724]
probably include CSS code in here as well, to make it more clear, instead of the entries within the `class`-attribute.

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/1629#discussion_r1369697205_

**Comment by mfranzke** [comment]
> But shouldn't the users use the data-* attributes?
> 
> Or do you mean the `scss` mixin we are using?

sorry, my comment should've been way more clearer: It's about the class-attributes values

**Comment by nmerget** [comment]
done: https://db-ui.github.io/mono/review/main/foundations/icons/custom-icons?current=css
