### ISSUE TITLE
several component pages are missing

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#1762]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

The brand overview page is missing. Open https://db-ui.github.io/mono/version/v0.0.57/components/brand/overview

### Expected Behaviour

The page would get displayed.

### Browser version

None

**Comment by mfranzke** [comment]
@snahn2209 could you please add further findings here?

**Comment by snahn2209** [comment]
> ### Reproduction case
> The brand overview page is missing. Open https://db-ui.github.io/mono/version/v0.0.57/components/brand/overview
> 
Also missing: 
- [ ] header overview (https://db-ui.github.io/mono/review/main/components/header/overview)
- [ ] page overview (https://db-ui.github.io/mono/review/main/components/page/overview)
- [ ] icon overview (https://db-ui.github.io/mono/review/main/components/icon/overview)

**Comment by d-koppenhagen** [comment]
Updated list off missing components:

- [DBBrand](https://db-ui.github.io/mono/review/main/components/brand/overview)
- [DBHeader](https://db-ui.github.io/mono/review/main/components/header/overview)
- [DBPage](https://db-ui.github.io/mono/review/main/components/page/overview)
