### ISSUE TITLE
test(a11y): Drawer doesn't get attention by screenreader users

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2035]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

- Open https://db-ui.github.io/mono/review/main/components/drawer
- Interact with one of the buttons to open the drawer
- The opened drawer isn't getting announced to screenreader users
- The focus isn't moved to the drawers content

### Expected Behaviour

Screenreader users would know the drawers state (like that it has been opened).

### Browser version

None

### Add any other context about the problem here.

[WCAG 4.1.3 Status Messages](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html)

**Comment by nmerget** [comment]
This issue could be tricky... https://adrianroselli.com/2020/10/dialog-focus-in-screen-readers.html
