### ISSUE TITLE
test(a11y): Label is being announced twice for Radio and Checkbox elements

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2037]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

- Open https://db-ui.github.io/mono/review/main/components/radio?page=tonality or https://db-ui.github.io/mono/review/main/components/radio?page=tonality
- The label would get announced twice by the screenreader, one as the label for the `input`-element and then again afterwards

### Expected Behaviour

The `label` would only get announced once as the label for the `input`-element.

### Browser version

None

### Add any other context about the problem here.

_WCAG 3.3.2 Labels or Instructions_

We maybe would need to move the `input` out of the `label`-element for this to get solved.

**Comment by nmerget** [comment]
@mfranzke how can we test this?

Based on the tree it should work 
![image](https://github.com/db-ui/mono/assets/104347736/0bde76cd-3d95-4ff5-82a2-37dba5b77ae9)

**Comment by mfranzke** [comment]
> @mfranzke how can we test this?
> 
> Based on the tree it should work ![image](https://private-user-images.githubusercontent.com/104347736/313644449-0bde76cd-3d95-4ff5-82a2-37dba5b77ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODA2NDksIm5iZiI6MTcxMDc4MDM0OSwicGF0aCI6Ii8xMDQzNDc3MzYvMzEzNjQ0NDQ5LTBiZGU3NmNkLTNkOTUtNGZmNS04MmEyLTM3ZGJhNWI3N2FlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNjQ1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDEwMzIxYjY2ZWE1OTYxNTQ1NmM5YmFiNWM0YzgyZGIwOWE0MmM3ZTI3Y2E5NTgyYjE5OTJkZWU3N2VlZTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KBWNrLME1k4UXcy_kX8h-ofh7VHNgRFkKy0g34khJmw)

I know, that's the feedback I got by a screenreader user (I sadly don't remember whether he was using NVDA or JAWS screenreader, but I could ask, and even also verify whether it appears with VoiceOver as well).

**Comment by mfranzke** [comment]
> > @mfranzke how can we test this?
> > Based on the tree it should work ![image](https://private-user-images.githubusercontent.com/104347736/313644449-0bde76cd-3d95-4ff5-82a2-37dba5b77ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODA2NDksIm5iZiI6MTcxMDc4MDM0OSwicGF0aCI6Ii8xMDQzNDc3MzYvMzEzNjQ0NDQ5LTBiZGU3NmNkLTNkOTUtNGZmNS04MmEyLTM3ZGJhNWI3N2FlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNjQ1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDEwMzIxYjY2ZWE1OTYxNTQ1NmM5YmFiNWM0YzgyZGIwOWE0MmM3ZTI3Y2E5NTgyYjE5OTJkZWU3N2VlZTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KBWNrLME1k4UXcy_kX8h-ofh7VHNgRFkKy0g34khJmw)
> 
> I know, that's the feedback I got by a screenreader user (I sadly don't remember whether he was using NVDA or JAWS screenreader, but I could ask, and even also verify whether it appears with VoiceOver as well).

Oh shooot, VoiceOver wouldn't be of any help for you …

**Comment by nmerget** [comment]
Based on our tests for the most common combination we are able to test:

Windows + NVDA this shouldn't be the case anymore: https://github.com/db-ui/mono/blob/main/showcases/screen-reader/__snapshots__/windows/chromium/DBRadio-should-label-duplicated-arrows-.txt
