### ISSUE TITLE
Button: `type` is not specified in a lot of cases

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2038]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Currently the buttons `type` is not specified in a lot of places, whereas this would lead to that a `submit` type (default) would get presumed.

### Expected Behaviour

Buttons of `type` button should actually get that attribute defined.

### Browser version

None

**Comment by nmerget** [comment]
We should use `type="button"` as a default, the HTML default `type="submit"` makes no sense for a modern design system

**Comment by mfranzke** [comment]
> We should use `type="button"` as a default, the HTML default `type="submit"` makes no sense for a modern design system

I'm still struggling with this, but hey …

**Comment by annsch** [comment]
In the current version of @db-ui/XX-components the default type for `button` is 'button'. This is not standard behaviour according to https://developer.mozilla.org/de/docs/Web/HTML/Element/button#type and leads to misfunction in standard html cases as forms with buttons that previously did not need to specify the type.

I made a simple poll in my project team and the majority of my colleagues share my opinion :)

**Comment by mfranzke** [comment]
> ![Image](https://github.com/user-attachments/assets/a1686b43-0619-4275-9ded-064eddd2e5a5) [ ![Image](https://github.com/user-attachments/assets/a1686b43-0619-4275-9ded-064eddd2e5a5) ](https://private-user-images.githubusercontent.com/335483/410508221-a1686b43-0619-4275-9ded-064eddd2e5a5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4NjE2MzIsIm5iZiI6MTczODg2MTMzMiwicGF0aCI6Ii8zMzU0ODMvNDEwNTA4MjIxLWExNjg2YjQzLTA2MTktNDI3NS05ZGVkLTA2NGVkZGQyZTVhNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNlQxNzAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODE4OThlODVlNGY2ZmJjZDdjZjkyNjA2NGIwNjJmMjllY2ViMThlMTNlYzYyNGRjZDJhNzMzZWQ1MGE0YmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xT9FD2aTXZik4H5Ww7ggugxNcS5XCZkTgLHBiXrFJzo) [ ](https://private-user-images.githubusercontent.com/335483/410508221-a1686b43-0619-4275-9ded-064eddd2e5a5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4NjE2MzIsIm5iZiI6MTczODg2MTMzMiwicGF0aCI6Ii8zMzU0ODMvNDEwNTA4MjIxLWExNjg2YjQzLTA2MTktNDI3NS05ZGVkLTA2NGVkZGQyZTVhNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNlQxNzAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODE4OThlODVlNGY2ZmJjZDdjZjkyNjA2NGIwNjJmMjllY2ViMThlMTNlYzYyNGRjZDJhNzMzZWQ1MGE0YmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xT9FD2aTXZik4H5Ww7ggugxNcS5XCZkTgLHBiXrFJzo)

@dkolba who told you ?

**Comment by nmerget** [comment]
Most Design Systems use `type=button` as default, see the examples:

https://react.carbondesignsystem.com/?path=/story/components-button--default
https://mui.com/material-ui/react-button/

I think most buttons in modern Web Apps are used as `type=button`. Anyways you should add your correct type to avoid such problems: https://www.w3schools.com/Tags/att_button_type.asp#:~:text=type%20of%20button.-,Tip,-%3A%20Always%20specify

But I found a great [solution](https://github.com/reactstrap/reactstrap/issues/382#issuecomment-290830943), by adding `type=button` only if `onClick` or `click` is passed we could keep `type=sumbit` empty :)

`type={props.type ?? (props.onClick ?? props.click) ? "button" : "submit"}`

**Comment by mfranzke** [comment]
> Most Design Systems use `type=button` as default, see the examples:
> 
> https://react.carbondesignsystem.com/?path=/story/components-button--default https://mui.com/material-ui/react-button/
> 
> I think most buttons in modern Web Apps are used as `type=button`. Anyways you should add your correct type to avoid such problems: https://www.w3schools.com/Tags/att_button_type.asp#:~:text=type%20of%20button.-,Tip,-%3A%20Always%20specify
> 
> But I found a great [solution](https://github.com/reactstrap/reactstrap/issues/382#issuecomment-290830943), by adding `type=button` only if `onClick` or `click` is passed we could keep `type=sumbit` empty :)
> 
> `type={props.type ?? (props.onClick ?? props.click) ? "button" : "submit"}`

in the future, it won't be (just) JavaScript event handlers, but [`command`](https://developer.mozilla.org/en-US/docs/Web/API/Invoker_Commands_API) and [`popovertarget`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#popovertarget), but I like the idea.
