### ISSUE TITLE
Components: problems with `id`-attribute ?

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2050]
@nmerget I just recognized that we use the attribute `id` on the outer components element for `checkbox` and `radio` that we actually transfer to the native element – this might lead to that the `id` would be on two elements afterwards (at least for frameworks like e.g. Angular in which context the outer element would still render), wouldn't it ?

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/2016#discussion_r1444267168_

**Comment by nmerget** [comment]
#2017
