### ISSUE TITLE
Ignore major dependency updates for JS frameworks

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#208]
Specifically for the JS frameworks (Angular, Vue, React) that we're providing showcases for, it's always about the current and the LTS version; in these cases we don't want to be flooded by PRs that include major version updates, that would also increase the major version for the LTS folders.

The easiest might be to deactivate major version updates specifically for these frameworks dependencies in total, as we would be aware and need to a lot of more work than just a PR to provide a new version, both in our output targets, as well as the showcase folders.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

This would be a followup to the existing entries: https://github.com/db-ui/mono/blob/main/.github/dependabot.yml#L21

**Comment by nmerget** [comment]
I guess we don't need it if we move them to a new repo: https://github.com/db-ui/mono/issues/700

**Comment by mfranzke** [comment]
> I guess we don't need it if we move them to a new repo: #700

valid point. Let's wait before closing this until we've moved it (most likely this will be sooner than later, if you're working on it 😜).
