### ISSUE TITLE
Input: `value` gets set for "floating label" variant on detail page

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2140]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

The input component in the "floating label" variant within the "Variant label" section is displayed and behaves differently on the overview page than in the detail page, compare https://db-ui.github.io/mono/version/v0.0.63/components/input/overview#:~:text=Variant%20Label,-Label (overview page) to https://db-ui.github.io/mono/version/v0.0.63/components/input/overview?page=variant%20label (detail page)

On the overview page the `placeholder` doesn't get displayed at all, but only the label, whereas in the detail page it's `value` gets set to the value of the `placeholder`-attribute.

### Expected Behaviour

They would get displayed and behave equally.

### Browser version

None

**Comment by nmerget** [comment]
Overview: 
![image](https://github.com/db-ui/mono/assets/104347736/2ebbb85f-ea78-4a3e-97e0-912962d5fccb)

Detail:
![image](https://github.com/db-ui/mono/assets/104347736/c266b67f-7f07-4b1d-a373-6d8c77e835ee)
