### ISSUE TITLE
Global style definitions

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2252]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

It seems a global style definition coming from `@db-ui/components/build/styles/db-ui-42-rollup` (
![image](https://github.com/db-ui/mono/assets/161047514/f923e48b-f552-4529-bc7e-1750563c96c4)
) is making font-size inheritance impossible unless we explicitly use `font-size: inherit | actual value` to child elements (which acutally beats the purpose of inheritance in CSS).

Steps to reproduce:

1. Import `@db-ui/components/build/styles/db-ui-42-rollup` from the DB UI library in order to gain access to combined dependencies like variables, colors and tonality and all components
2. Generate a simple HTML block containing nested elements where the root element has a defined font-size to a value X, e.g. 			
```html
<style type="text/css">
  .test-class {
    font-size: 12px;
  }	
</style>
<div className="test-class">
  <ul>
    <li>List item 1</li>
    <li>List item 2</li>
  </ul>
  <p>Test paragraph</p>
</div>
```

### Expected Behaviour

`font-size` inheritance should be working without having to use the `inherit` keyword or similar.

### Screenshots

I've attached screenshots in the "Reproduction case". If you want, in the future I can attach them here only, just let me know.

### Browser version

None

**Comment by mfranzke** [comment]
@nmerget you might be best to answer this and we should probably find a way to document it as well.

**Comment by nmerget** [comment]
We released https://github.com/db-ui/mono/releases/tag/v0.0.66, which should cover the issue.

We add the documentation how to change font-sizes: https://db-ui.github.io/mono/review/main/foundations/font-sizes/readme

We recommend using the class or placeholder to change the `line-height` and the icon size as well. Otherwise there could be issues with the layout/components
