### ISSUE TITLE
DBNavigationItem doesn't auto-close

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2276]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

After clicking on a DBNavigationItem component and moving to another route, the navigation item stays open. This behaviour of navigation items staying open after clicking on them is consistent, regarding if a route has been changed or not.

Code example:
```jsx
<DBMainNavigation>
	<DBNavigationItem
		slotSubNavigation={
			<>
				<DBNavigationItem>
					<Link to="/a">
						A
					</Link>
				</DBNavigationItem>
				<DBNavigationItem>
					<Link to="/b">
						B
					</Link>
				</DBNavigationItem>
			</>
		}
	>
		{t('navigation_node_crud')}
	</DBNavigationItem>
</DBMainNavigation>
```

The same behaviour can be replicated in the library docs https://db-ui.github.io/mono/review/main/components/main-navigation/overview#.

### Expected Behaviour

Navigation items are closed when clicking on them (maybe automatically or provide a prop to control such functionality, something like "shouldAutoClose: boolean;"). 

### Browser version

None

**Comment by nmerget** [comment]
@MihajloLazar1 thanks for this.

I thought about the "auto-close" as well 👍 

I guess the best would be a prop like you suggested

**Comment by MihajloLazar1** [comment]
@nmerget Sounds great, thanks :)
