### ISSUE TITLE
DBMainNavigation incorrect documentation example

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2277]
### Which generators are impacted?

- [ ] All
- [X] HTML
- [X] React
- [X] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

If you visit the `DBMainnavigation` documentation page (https://db-ui.github.io/mono/review/main/components/main-navigation/overview), you'll notice the code example are incorrect. There seems to be missing a lot of sub-components.

![image](https://github.com/db-ui/mono/assets/161047514/37679594-ec3d-43aa-851d-1f6cb52302fe)

### Expected Behaviour

Code examples always replicate needed components structure and props in order to achieve the documented examples.

### Browser version

None

**Comment by nmerget** [comment]
Yes, some of the nested components are missing. We will add those examples.
For now, you can check the showcase to see some example:
https://github.com/db-ui/mono/blob/main/showcases/react-showcase/src/components/main-navigation/index.tsx#L13
