### ISSUE TITLE
Pre-commit: integrate package.json sorting

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#231]
https://github.com/un-ts/prettier
~~https://github.com/keithamus/sort-package-json~~

**Comment by nmerget** [comment]
https://github.com/un-ts/prettier <- could be an option, as well

**Comment by d-koppenhagen** [comment]
Just want to sort the dependencies? Here is a zero dependency solution: https://dev.to/cbillowes/how-to-sort-your-packagejson-dependencies-1gi1 ;-)

**Comment by mfranzke** [comment]
> Just want to sort the dependencies? Here is a zero dependency solution: https://dev.to/cbillowes/how-to-sort-your-packagejson-dependencies-1gi1 ;-)

Nice idea! From time to time we had even also just the dependencies being resorted on an upfollowing install because somebody might have added a dependency by hand.
In this case it's more like could we ensure a general structure, that even also prioritizes the most relevant aspects to find easily in this file.
