### ISSUE TITLE
DBTooltip / DBPopover - auto-positioning

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2314]
The `placement` prop for both components is working fine, but I was wondering if it would be possible to add another "auto" option as prop value which would prevent component's content to leave the viewport and automatically reposition the tooltip to the side where there is enought space?

Something similar to this https://floating-ui.com/docs/autoplacement or https://mui.com/material-ui/api/popper/#popper-prop-placement.

**Comment by nmerget** [comment]
Hey @MihajloLazar1, yes this is something we want to add.
I did it already for the Sub-Navigation: https://github.com/db-ui/mono/pull/2167
Hope we can merge this soon and then we could apply the same logic for the tooltip/popover.
