### ISSUE TITLE
Enable custom data-attributes for components

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2352]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [X] Angular
- [X] Vue
- [X] Web components
- [ ] Power Apps

### Reproduction case

For e.g. test automation we need the possibility to set custom HTML attributes to components, e.g. `<DBButton data-testid="myButton"></DBButton>`

### Expected Behaviour

All custom HTML attributes set on db-components should be passed down to the HTML elements (e.b. `<button>`)

### Browser version

None

**Comment by nmerget** [comment]
@annsch which version do you use?

https://github.com/db-ui/mono/blob/main/packages/components/src/utils/index.ts#L70 <- all `data-` attributes should be parsed
