### ISSUE TITLE
feat: provide individual components for angular as `standalone` components

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#237]
With the [introduction of Standalone Components with Angular 14](https://angular.io/guide/standalone-components), components can be imported and tree-shaked individually without the need of a wrapping module such as `DBUIElementsModule`.

It would be great if all components can be marked as `standalone` and imported individually.

compare to https://github.com/db-ui/elements/issues/605

**Comment by annsch** [comment]
Actually this feature/option seems to be not fully implemented: 
https://github.com/BuilderIO/mitosis/issues/960
We should observe their solution first.

**Comment by annsch** [comment]
@nmerget according to Dannys Feedback is this really nice to have or a must have?

**Comment by nmerget** [comment]
You are right, it's Angular so we could add the label "not supported" :P

We can remove the label, let's finish the input for Angular and Vue.

**Comment by d-koppenhagen** [comment]
I will give this issue a push since we ware st Angular 17 now. Standalone components are the recommended way in Angular now. Angular will drop or at least deprecate NgModules in the future.

**Comment by d-koppenhagen** [comment]
Another point: It produces less boilerplate code and makes integration and testing easier.

**Comment by d-koppenhagen** [comment]
If you give me a quick into about the mechanisms of mitosis here, I can probably also take over.

**Comment by d-koppenhagen** [comment]
@annsch I think I managed it. Fingers crossed.
