### ISSUE TITLE
docs(main navigation / Within sub-navigation): `RouterLink` must be wrapped by `DBNavigationItem` individually

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2431]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

tbd

### Expected Behaviour

tbd

### Browser version

None

**Comment by nmerget** [comment]
We have a ["How to use"](https://db-ui.github.io/mono/review/feat-color-palette/components/main-navigation/how-to-use?current=vue-router-and-active-state-handling) file, which describes this

**Comment by mfranzke** [comment]
@bruno-sh, I assume, that this issue is fixed by that newly provided file.
