### ISSUE TITLE
docs(DBDrawer): value `open` must be set on `openDrawer.value`

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2437]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

_tbd_

### Expected Behaviour

_tbd_

### Browser version

None

**Comment by nmerget** [comment]
@bruno-sch can you explain this issue?
