### ISSUE TITLE
docs(DBDrawer): prop `withCloseButton` seems misleading

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2438]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

_tbd_

### Expected Behaviour

_tbd_

### Browser version

None

### Add any other context about the problem here.

would also expect a close-button if the prop is not set

**Comment by nmerget** [comment]
@bruno-sch can you explain this issue?

**Comment by bruno-sch** [comment]
@nmerget of course:

Everything is right with the property.

As a user, I would expect a close button to be displayed in the drawer by default. So that it doesn't have to be displayed via a Boolean prop. But that's my subjective feedback and of course a conceptual question...

**Comment by nmerget** [comment]
We should discuss this with design, maybe we can change the default. It makes more sense for me as well

**Comment by nmerget** [comment]
Removed it because of accessibility issues
