### ISSUE TITLE
New linters/formatters 

### ISSUE THREAD

**Issue by nmerget** [db-ui/mono#244]
We should add a linter or formatter for shell scripts e.g. https://github.com/un-ts/prettier.

https://github.com/kucherenko/jscpd <- is also a good option

**Comment by mfranzke** [comment]
It's also part of [super-linter](https://github.com/marketplace/actions/super-linter#supported-linters), so that's another "validation" for this to be a good solution.

**Comment by nmerget** [comment]
I won't recommend super-linter, tried to add it to our pipeline, but it is just a blown-up monster with less control.

Moreover, I suggest that we search for linters that can be used in a node environment. A lot of the linters in super-linter are written in go and shipped in a container which makes issues harder to find.

**Comment by mfranzke** [comment]
> I won't recommend super-linter, tried to add it to our pipeline, but it is just a blown-up monster with less control.
> 
> Moreover, I suggest that we search for linters that can be used in a node environment. A lot of the linters in super-linter are written in go and shipped in a container which makes issues harder to find.

Totally agreed – there might have been a misunderstanding: I didn't want to to imply, that we should use `super-linter` in our product, but as it's used in other projects quite regularly and it's a "standard", having `super-linter` including `jscpd` only validates that tools decision, but I didn't want to imply that this would lead us to use the full monty `super-linter`.
