### ISSUE TITLE
DBHeader: the value from the prop `burgerMenuLabel` is not visible

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2445]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

DBHeader: the value from the prop `burgerMenuLabel` is rendered in the markup, but is not visible on the page

### Expected Behaviour

The markup provided should get shown on the page.

### Browser version

None

**Comment by nmerget** [comment]
It's only for screenreaders it shouldn't be visible
