### ISSUE TITLE
no auto-correction for component props

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2453]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [X] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

no auto-correction for component props

### Expected Behaviour

component props would get an auto-correction.

### Browser version

None

### Add any other context about the problem here.

Might be related to https://github.com/db-ui/mono/issues/2441

see also https://github.com/db-ui/mono/issues/2428

**Comment by nmerget** [comment]
@annsch Can you provide more information?

![image](https://github.com/db-ui/mono/assets/104347736/5b744e84-3535-4ac6-b59b-0b09d208cdc9)
I tested it and got all available props as suggestion.

**Comment by nmerget** [comment]
Maybe you need the VSCode Extension: https://angular.io/guide/language-service
