### ISSUE TITLE
docs: missing documentation for navigation directives

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2454]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [X] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

missing docs for navigation directives

### Expected Behaviour

documentation would exist.

### Browser version

None

**Comment by nmerget** [comment]
Will be solved with https://github.com/db-ui/mono/pull/1897

**Comment by nmerget** [comment]
solved by https://github.com/db-ui/mono/pull/1897
