### ISSUE TITLE
db-main-navigation: directive import leads to error

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2455]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [X] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

db-main-navigation: directive import leads to error: An unhandled exception occurred: Missing "./components/header/ActionBar.directive" specifier in "@db-ui/ngx-components" package See "/private/var/folders/t6/wg_h_yhn4bb6_7g9yn30qqmw0000gn/T/ng-nNRT5n/angular-errors.log" for further details.

### Expected Behaviour

No error would come up.

### Browser version

None

**Comment by nmerget** [comment]
Added directives to `index.ts` in this [lines](https://github.com/db-ui/mono/blob/main/packages/components/scripts/post-build/angular.js#L176-L179), should be fixed
