### ISSUE TITLE
docs: incorrect props

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2459]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

The [DBHeader](https://db-ui.github.io/mono/version/v0.0.68-beta/components/header/overview) usage example currently has incorrect props. `slotBrand`, `slotMetaNavigation`, `slotCallToAction`, `slotActionBar` should be `brand`, `metaNavigation`, `callToAction`, `actionBar` respectively

### Expected Behaviour

The listed props would actually work.

### Browser version

None

**Comment by nmerget** [comment]
Closed by https://github.com/db-ui/mono/pull/1897
