### ISSUE TITLE
Documentation page should be linked in the `README.md`

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2460]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Documentation page should be linked in the README.md as well. Its easy to miss in the description only

### Expected Behaviour

Documentation page is linked in the README.md as well.

### Browser version

None

**Comment by nmerget** [comment]
https://github.com/db-ui/mono/pull/1897
