### ISSUE TITLE
db-input: HTML validation is supersedes data-variant

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2471]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

We're using react-hook-forms and Zod for validation and schema and do not like to duplicate validations for form elements (e.g. <input minLength=3>). Currently HTML validation is more important than our custom validation: elements with `data-variant="critical"` are displayed as valid when simple HTML validation returns true:

![Bildschirmfoto 2024-04-08 um 12 53 18](https://github.com/db-ui/mono/assets/2963522/828ad55d-be2e-4921-ba54-8bd334c42649)
![Bildschirmfoto 2024-04-08 um 12 43 46](https://github.com/db-ui/mono/assets/2963522/9d9b7c6c-a94b-4ec2-ac22-315745c00abb)
![Bildschirmfoto 2024-04-08 um 12 43 08](https://github.com/db-ui/mono/assets/2963522/7c1730a9-64e2-4ff8-9371-99cedec262a4)

### Expected Behaviour

`data-variant` prop should overwrite HTML validation via `:user-valid`

### Browser version

None

**Comment by mfranzke** [comment]
@annsch what about switching to modern solutions (like the built-in form validation)?

**Comment by annsch** [comment]
@mfranzke this could be our preferred solution if HTML supported complex business logic. This example is only for demonstration purpose. We have to build complex validation logic which isn't done by only setting min- and maxLength ...

**Comment by mfranzke** [comment]
> @mfranzke this could be our preferred solution if HTML supported complex business logic. This example is only for demonstration purpose. We have to build complex validation logic which isn't done by only setting min- and maxLength ... e.g. denpndency between two ore more form fields

Complex regarding providing a pattern? Or doing some other fancy stuff, and than only wanting to define a valid or invalid on that form field?

**Comment by annsch** [comment]
> > @mfranzke this could be our preferred solution if HTML supported complex business logic. This example is only for demonstration purpose. We have to build complex validation logic which isn't done by only setting min- and maxLength ... e.g. denpndency between two ore more form fields
> 
> Complex regarding providing a pattern? Or doing some other fancy stuff, and than only wanting to define a valid or invalid on that form field?

the latter ...

**Comment by annsch** [comment]
no, I haven't, is this the preferred solution?

**Comment by mfranzke** [comment]
> no, I haven't, is this the preferred solution?

yes, I would suggest that one, as it includes both the visual as well as the semantic annotation.

**Comment by mfranzke** [comment]
And we need to further update our documentation and make these things much clearer (with our naming of those aspects as well).
