### ISSUE TITLE
Style prop available but not applied

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2499]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

A very basic reproduction case:

```jsx
<DBTextarea
    label=""
    rows={1}
    style={{
	paddingTop: 0,
	paddingBottom: 0
    }}
/>
```

### Expected Behaviour

Custom inline styles to be applied.

### Browser version

None

### Add any other context about the problem here.

It looks like custom inline styles are not being applied to the DBTextarea component (I'm guessing other components have the same issue). Can you please check this out?

**Comment by nmerget** [comment]
We deployed [0.0.72](https://github.com/db-ui/mono/releases/tag/v0.0.72) which includes this [fix](https://github.com/db-ui/mono/pull/2337) and resolves this [issue](https://github.com/db-ui/mono/issues/2315) which might be the same right?

**Comment by nmerget** [comment]
![image](https://github.com/db-ui/mono/assets/104347736/0d1528a6-5f2f-4854-992b-c6ecfcef2c63)
I tested it in a example repo, it should look like this

**Comment by MihajloLazar1** [comment]
Yes, tested it locally and seems to be working fine, thank you :). Feel free to close the issue.
