### ISSUE TITLE
DBButton: shouldn't `<db-button>` be squared when only displaying icons?

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2534]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

```tsx
<DBButton icon="edit"></DBButton>
<DBButton size="small" icon="edit"></DBButton>
```

![Bildschirmfoto 2024-04-16 um 11 56 38](https://github.com/db-ui/mono/assets/2963522/bbc866b4-64b7-4444-9b1c-3039ac355d27)

### Expected Behaviour

DBButton with only Icon should have the possibility to work as squared button as well or – if this is not specified by UX team – in case with only icon, there should no margin-inline-end style

### Browser version

None

**Comment by mfranzke** [comment]
@annsch thanks for your feedback.

Actually in this case the alternative text would be missing and this wouldn't be accessible. There is actually a property by which you could configure the button to not display that neccessary text that would need to get provided: noText

**Comment by mfranzke** [comment]
@annsch did that fix the problem ?

**Comment by annsch** [comment]
did not see the noText prop :(
