### ISSUE TITLE
Vue: slots not working with v0.1.0

### ISSUE THREAD

**Issue by andre-bartak** [db-ui/mono#2544]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Slots like 'call-to-action' in the DBHeader component do not work anymore.
Digging into to ui lib code the naming of the internal slot of DBHeader seems to have changed to 'calltoaction'.

This change seems to apply to all slots names in the db-ui lib.

### Expected Behaviour

Slots should be available with a name as documented

### Browser version

None

**Comment by nmerget** [comment]
There is a bug in [mitosis](https://github.com/BuilderIO/mitosis/pull/1391). I fixed it already, it needs some iteration, but we will see

**Comment by mfranzke** [comment]
@andre-bartak could you please retest with the new version 0.1.1 ?

**Comment by andre-bartak** [comment]
Can confirm, slots working again with the intended name convention :-)
