### ISSUE TITLE
Add more a11y tests via axe-core

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2571]
To prevent problems like e.g. https://github.com/db-ui/core/issues/820 we should further optimize our testing and linting.

see also https://github.com/db-ui/mono/issues/2579

**Comment by nmerget** [comment]
https://github.com/marketplace/actions/lighthouse-ci-action

or 

https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md#prerequisites

**Comment by mfranzke** [comment]
> I tested with lighthouse ci, and it takes very long in the CI.
> 
> Currently, we only need the accessibility feature which is provided by axe-core, which is already in our repo via playwright. I will rename this issue and include axe to our showcase tests to fix those problems.

I meant to use `lighthouse` not just for a11y, but also the other nice included test types, but let's focus on a11y first of all. I've added a new lighthouse issue independently: https://github.com/db-ui/mono/issues/2582
