### ISSUE TITLE
decide to use either npm i or npm ci during CI/CD

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#258]
Within other installations we were using `npm ci`, and now only `npm i` within our CI/CD scripts. Let's find out what's best and document it. Most likely we would need `npm ci` for comparable builds (as only the lock file guarantees consistent versions).

**Comment by nmerget** [comment]
We should consider if we still need "init-cache" action or if "bahmutov-npm-install" is enough

**Comment by nmerget** [comment]
outdated
