### ISSUE TITLE
Form Components: Placeholder accessibility issue

### ISSUE THREAD

**Issue by nmerget** [db-ui/mono#2587]
Currently, there is an accessibility issue with our placeholders for all form components. 
We need to discuss how to handle them properly.

See this as references:

- https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/
- https://accessibleweb.com/question-answer/does-placeholder-text-need-to-meet-color-contrast-requirements/#:~:text=Answer,minimum%20contrast%20success%20criterion%20(1.4.

**Comment by mfranzke** [comment]
see also https://github.com/db-ui/design-feedback/issues/134
