### ISSUE TITLE
Export all relevant constants (variants, colors, icons, semantics, etc.) for further use in typescript projects

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2638]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

We use Storybook for our components. For options that should be displayed as dropdown list we need all possible enums as const export to list all possibilities, e.g. for variants, semantics, icon names etc.
Currently these aren't exported from @db-ui/react-components

### Expected Behaviour

E.g. 
```
export type ButtonVariantsType = 'outlined' | 'brand' | 'filled' | 'ghost';
```

should also export
```
export const ButtonVariantsTypeList = ['outlined', 'brand', 'filled', 'ghost'];
```

### Browser version

None

**Comment by nmerget** [comment]
Yes, we can do this.

We need to provide it like this:

````
export const ButtonVariantsTypeList = ['outlined' , 'brand' , 'filled' , 'ghost'] as const;
export type ButtonVariantsType = typeof ButtonVariantsTypeList[number];
````

**Comment by annsch** [comment]
> Yes, we can do this.
> 
> We need to provide it like this:
> 
> ```
> export const ButtonVariantsTypeList = ['outlined' , 'brand' , 'filled' , 'ghost'] as const;
> export type ButtonVariantsType = typeof ButtonVariantsTypeList[number];
> ```

perfect <3
