### ISSUE TITLE
DBNotification: why does variant "overlay" omits link property?

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2651]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

DBNotification "overlay" is not possible with links - why?

### Expected Behaviour

DBNotification "overlay" should not have an impact on displayed content.

### Browser version

None

**Comment by nmerget** [comment]
This was a decision from design, not providing the link for variant `overlay`. Maybe the requirements changed, there is a new example in the Figma library, created two weeks ago. I can change the layout to enable the combination of `variant=overlay` and link
