### ISSUE TITLE
Improve performance of :has css-selector

### ISSUE THREAD

**Issue by bruno-sch** [db-ui/mono#2698]
We should check whether the global use of the css-selector `:has` has a noticeable / measurable influence on the rendering performance.

If this is the case, we should look for a solution to reduce the global (e.g. root-level) usage of the `:has` selector as much as possible.

Especially affected files:
- packages/components/src/components/badge/badge.scss
- packages/components/src/components/tooltip/tooltip.scss

**Comment by mfranzke** [comment]
@bruno-sch have you already measured the impact and if so, which tools have you used ?
