### ISSUE TITLE
Add tailwind.config.ts to foundations

### ISSUE THREAD

**Issue by IOIO72** [db-ui/mono#2709]
Add `tailwind.config.ts` to  https://github.com/db-ui/mono/tree/main/packages/foundations/tailwind

Use `Config` types to introduce typing into the config file: `import type { Config } from 'tailwindcss';`

When using the default configuration type of Tailwind, the linter shows some errors in the [tailwind-tokens.json](https://github.com/db-ui/mono/blob/main/packages/foundations/tailwind/tailwind-tokens.json). This could be an error or the types need to be extended.

**Comment by mfranzke** [comment]
@IOIO72 thanks a lot for your feedback. @nmerget will have a look at it.

**Comment by IOIO72** [comment]
Thanks,

btw, it seems that Tailwind recommends using zeros as strings instead of numbers.

`0: '0',`
`none: '0',`
