### ISSUE TITLE
Label of DBSwitch is pulled apart

### ISSUE THREAD

**Issue by bruno-sch** [db-ui/mono#2715]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

The **DBSwitch** component is automatically as wide as the container. This results in a sometimes very large, incorrect distance between the switch button and the label. 

This only happens when the parent container is set to `display: block` or `inline`. The display error does not occur with `display: flex`.

Possible cause is the following line of CSS applied to `.db-switch` itself: `justify-content: flex-start;`

[Example at codesandbox](https://codesandbox.io/p/sandbox/angry-fermat-hmg89p?file=%2Fsrc%2Findex.tsx)

### Expected Behaviour

The label is displayed directly next to the switch itself without unnecessary spacing.

### Screenshots

<img width="771" alt="Bildschirmfoto 2024-06-04 um 16 44 07" src="https://github.com/db-ui/mono/assets/163294364/0d4ac62b-c829-43de-9883-167d8e733a58">

### Browser version

None

**Comment by mfranzke** [comment]
@bruno-sch the `label`-element itself is only an inline element – are you referring to a specific framework component, or am I missing something ? Or do you have a test case, out of a JSBin, https://vscode.dev/, etc.?

**Comment by bruno-sch** [comment]
@mfranzke as this is a css problem, the error should occur in every framework. By **label** I did not mean the `label` tag, but the text next to the switch button itself.

Live example: [Codesandbox](https://codesandbox.io/p/sandbox/angry-fermat-hmg89p)
