### ISSUE TITLE
Invalid CSS is generated: Unexpected token Function("var")

### ISSUE THREAD

**Issue by Mydayyy** [db-ui/mono#2727]
Greetings

### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

The file `db-ui-42.css` contains invalid css. 

1. Search for this selector inside the file: `dialog:not([data-backdrop=none])::backdrop`
2. Locate the `background-color` style inside the selector
3. That style is assigned the value `var(var(--db-current-color-enabled), var(--db-neutral-on-bg-enabled))` which is invalid
### Expected Behaviour

The file `db-ui-42.css` should not contain invalid css.

### Screenshots

![image](https://github.com/db-ui/mono/assets/8339771/c0c0a1d8-8778-45f1-a909-34972ea2f59c)
![Screenshot 2024-06-07 at 12 57 12](https://github.com/db-ui/mono/assets/8339771/2a67686a-1253-44d3-8c0a-d893d65b137c)

### Browser version

None

### Add any other context about the problem here.

The source of the problem can be found here: https://github.com/db-ui/mono/blob/c5b4478d08fdd293b19f0b661a42fc28223e4ca6/packages/components/src/styles/dialog-init.scss#L30

which in turns gets assigned the variable declared here: https://github.com/db-ui/mono/blob/c5b4478d08fdd293b19f0b661a42fc28223e4ca6/packages/components/src/styles/dialog-init.scss#L3

And ends up having the invalid nested `var(var(...` assignment

Best Regards
Mydayyy

**Comment by annsch** [comment]
I have the same problem in my project ;)

**Comment by dkolba** [comment]
Sass in one picture
![this-is-fine_wide-4a729b43a69f924bb86eb688b8f3bb38ff19be3b](https://github.com/db-ui/mono/assets/335483/df186ac0-2f15-4d2e-9cf6-b39dbf8f0cce)

**Comment by mfranzke** [comment]
> I have the same problem in my project ;)

what a coincidence
