### ISSUE TITLE
DBTag: provide overflow (tbd.)

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2734]
### Which generators are impacted?

- [ ] All
- [X] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

DBTag component can be displayed smaller than its containing text. In this case the inner text should not overflow outside of its parent div. Could you enable overflow: hidden or inherit for this component?

![Bildschirmfoto 2024-06-10 um 14 09 42](https://github.com/db-ui/mono/assets/2963522/6b9dc1d5-c387-4870-bb72-81bffd85b94b)

### Expected Behaviour

Text should not overflow outside when using DBTag

![Bildschirmfoto 2024-06-10 um 14 11 04](https://github.com/db-ui/mono/assets/2963522/8cfe4372-bb65-4448-b2fd-d70c145eb114)

### Browser version

None

**Comment by mfranzke** [comment]
@annsch thanks for your feedback. What's the use case for text being cropped in this case? It seems like that with some short words or phrases like these, even [`ellipsis`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow#ellipsis) wouldn't work.

**Comment by nmerget** [comment]
https://db-ui.github.io/mono/review/main/components/data-display/tag/overview?page=overflow <- there is an overflow property

**Comment by annsch** [comment]
did not see this property

**Comment by mfranzke** [comment]
> did not see this property

No problem, that's my job (or @nmerget's).
