### ISSUE TITLE
General use of components: use composition over configuration for components

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2746]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [X] Angular
- [X] Vue
- [x] Web components
- [ ] Power Apps

### Reproduction case

@db-ui often uses configuration over composition when consuming components by JS/TS Framewors like React, Angular or Vue. For example DBTooltip: the content is provided by prop "content". This is very restrictive, e.g. displaying custom HTML content in Tooltip components is not provided. 
For our application we need to display more than just text in a Tooltip, is it possible to discuss this behaviour in general? We'd prefer a more flexible use of this components by providing a component DOM tree like e.g. mantine is doing this:
https://mantine.dev/core/popover/

### Expected Behaviour

Enable composition over configuration for components

### Browser version

None

**Comment by mfranzke** [comment]
@annsch thanks a lot for your feedback. We're actually providing the exact same component that Mantine does: https://db-ui.github.io/mono/version/v0.1.5/components/utilities/popover/overview

**Comment by annsch** [comment]
omg, how did I miss this <3

**Comment by mfranzke** [comment]
> omg, how did I miss this <3

by us not documenting it enough.
