### ISSUE TITLE
docs: "How to use this in (…)" links missing category URL part

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#2773]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

The "How to use this in (...)" links like e.g. [How to use this in html](https://db-ui.github.io/mono/review/main/components/tooltip/how-to-use?current=html) within the code panel on https://db-ui.github.io/mono/version/v0.2.1/components/data-display/tooltip/overview are missing the components category part within the linked URL.

### Expected Behaviour

The link would get correctly resolved and the page would show up.

### Screenshots

<img width="346" alt="image" src="https://github.com/db-ui/mono/assets/787658/2c067e4e-264d-4621-aa18-9acac583fba4">

### Browser version

None

**Comment by nmerget** [comment]
This has been fixed for newer versions
