### ISSUE TITLE
DBPopover's open state can't be controlled by nested buttons 

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#2813]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Given the following example, the popover doesn't close on clicking the DBPopover childrens' buttons:

```tsx
const [isOpen, setOpen] = useState(false);

<DBPopover delay="fast" placement="bottom-start" open={isOpen}>
    {[10, 20, 30, 50, 100].map((pageSizeItem) => (
        <DBButton key={pageSizeItem} onClick={() => { setOpen(false); }}>
            {pageSizeItem}
        </DBButton>
    ))}
</DBPopover>

<DBButton onClick={() => setOpen(!isOpen)}>Open / close Popover</DBButton>
```

### Expected Behaviour

The popover should close

### Browser version

None

**Comment by nmerget** [comment]
`&:focus-within {
		> article {
			@extend %show-popover;
		}
	}`
	
The problem is the `focus-within` which would still be on the button. I will fix it
