### ISSUE TITLE
How to handle focus outline offset

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#290]
Currently we have focus outline offset -1, this leads to following behaviour when used without margin from containers:
![Bildschirm­foto 2023-01-27 um 08 55 37](https://user-images.githubusercontent.com/2963522/215036560-443cd79e-69b7-4387-98b5-b29d8bea895f.png)
![Bildschirm­foto 2023-01-27 um 08 55 46](https://user-images.githubusercontent.com/2963522/215036563-016d6ae7-cbc8-4e21-8c72-9c18a83bfc36.png)

**Comment by annsch** [comment]
@mfranzke fyi. Do you have a preferred solution? Maybe we could discuss this together?

**Comment by mfranzke** [comment]
I could've only found the declaration of `1px` instead of `-1px`:
https://github.com/db-ui/mono/blob/main/packages/foundations/scss/_init.scss#L5

**Comment by mfranzke** [comment]
obsolete by #1620
