### ISSUE TITLE
docs: Navigation "Show Code" hidden for version > 0.2.2 on GitHub pages

### ISSUE THREAD

**Issue by nmerget** [db-ui/mono#2945]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Goto [this](https://db-ui.github.io/mono/version/v0.2.2/components/feedback/notification/overview?page=content+-+variant%3Adocked). There is no "Show Code" button, but only on version > 0.2.2

### Expected Behaviour

The "Show Code" button should be available

### Screenshots

![image](https://github.com/user-attachments/assets/6eacfb89-7944-41e0-ae43-5dc4d826d124)

### Browser version

None

**Comment by bruno-sch** [comment]
@nmerget , this should be fixed by my already merged changes: https://github.com/db-ui/mono/issues/2863
