### ISSUE TITLE
DBDivider "margin" prop not clear

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2981]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

```jsx
<DBDivider variant="vertical" margin="some_value" />
```

### Expected Behaviour

I'm able to control margin of the component.

### Browser version

None

### Add any other context about the problem here.

In general, I'm not sure which values are allowed for the "margin" prop of the DBDivider component. I've tried different spacing values and other variables mentioned here https://db-ui.github.io/mono/version/v0.2.5/foundations/readme and here https://db-ui.github.io/mono/version/v0.2.5/foundations/variables/readme, but nothing worked so far.
Also, typescript allows only two values for that prop: "none" and "_".

Can you please provide an example which values can be used here?

**Comment by nmerget** [comment]
@MihajloLazar1 thanks for this hint. The implementation of the divider was very old. I updated the `margin` types based on our default `spacing` props.

**Comment by MihajloLazar1** [comment]
@nmerget great, thank you very much :).
