### ISSUE TITLE
Version switcher components not visible

### ISSUE THREAD

**Issue by Mishra115** [db-ui/mono#3008]
Components in the version switcher template are not visible until focused.

**ScreenShot**

![image](https://github.com/user-attachments/assets/1b898513-bc4e-4a15-a924-a443128393e2)

**Comment by mfranzke** [comment]
@Mishra115 thanks a lot for reporting this. What browser / OS combination are you using ?

**Comment by Mishra115** [comment]
> @Mishra115 thanks a lot for reporting this. What browser / OS are you using ?

Chrome
