### ISSUE TITLE
DBDrawer: change default close behaviour or enable custom close 

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#3108]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Currently the DBDrawer component is closed whenever any user clicks on the backdrop element. 

### Expected Behaviour

It should be possible to disable the close functionality for :backdrop elements as it is documented here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal

### Browser version

None

**Comment by mfranzke** [comment]
> Relates to #3258

https://github.com/db-ui/mono/issues/3258 provides a solution that's probably not as good as just controlling our individually integrated behaviour of closing a dialog that has been opened by `showModal()`.

**Comment by nmerget** [comment]
@annsch 

We send an event tothe `props.onClose(event)`:

````
	if (
				event === 'close' ||
				event.key === 'Escape' ||
				(event.target.nodeName === 'DIALOG' &&
					event.type === 'click' &&
					props.backdrop !== 'none')
			) {
				if (props.onClose) {
					props.onClose(event);
				}
			}
````

You should be able to open/close the drawer based on this event:


`<DBDrawer onClose={(event)=> event==="xxx" ? dontClose() : close()} ...>`
