### ISSUE TITLE
Colors messed up on Samsung Internet Browser

### ISSUE THREAD

**Issue by IOIO72** [db-ui/mono#3117]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Just view i.e. https://db-ui.github.io/mono/review/main/components/layout/drawer/overview on an Samsung Internet browser.

Backgrounds are transparent. Borders are missing, logo gets monochrome.

### Expected Behaviour

All colors, especially for backgrounds and borders should be present.

### Screenshots

![Screenshot_20240830_142128_Samsung Internet](https://github.com/user-attachments/assets/4e5662b1-1c61-4b17-a9e9-00ddb271a902)
![Screenshot_20240830_142137_Samsung Internet](https://github.com/user-attachments/assets/51ad2f1b-5ba0-4d58-b801-5cb16738f58e)

### Browser version

other

### Add any other context about the problem here.

I used **Samsung Internet 26** on a Samsung Galaxy S24 Ultra with Android 14.

Note: On mobile Samsung Internet is the third popular browser in Germany right after Chrome and Safari.

**Comment by mfranzke** [comment]
@IOIO72 thanks a lot for mentioning this. Samsung Internet still is some Chromium-versions behind the actual releases (the only source I could have found by a quick research was https://en.wikipedia.org/wiki/Samsung_Internet), so we'll add a warning to our users on this browser not being supported.

**Comment by IOIO72** [comment]
> @IOIO72 thanks a lot for mentioning this. Samsung Internet still is some Chromium-versions behind the actual releases (the only source I could have found by a quick research was https://en.wikipedia.org/wiki/Samsung_Internet), so we'll add a warning to our users on this browser not being supported at the moment.

I don't think, that a warning is the right decision. Many users simply use the pre-installed browsers on mobile devices. I assume, that a fix for the recent version of Samsung Internet won't be so complicated. I'd look into this as I find some time.
