### ISSUE TITLE
Add valid state to component "Select / Label above" (Figma)

### ISSUE THREAD

**Issue by vladi94** [db-ui/mono#3166]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Its not a bug - but an enhancement

### Expected Behaviour

Same valid state as for the inputs.

### Screenshots

<img width="293" alt="image" src="https://github.com/user-attachments/assets/b3673e74-f42c-4d30-8910-efb9c2a8b796">

### Browser version

None

### Add any other context about the problem here.

Would be very nice, since invalid is already available, and for instance, the valid state is already available for the inputs.
Without it, you actually can't design all valid options for a more complex form:
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/c219dcfe-9822-4f0f-929a-ef44cf550899">

**Comment by leape** [comment]
@vladi94 can you please create this as a [design issue](https://github.com/db-ui/design/issues)? thanks!

**Comment by vladi94** [comment]
@leape Did so, thanks. This (false) bug issue can be closed.
