### ISSUE TITLE
DBBadge: Numbers are not centered correctly 

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#3250]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

![Bildschirmfoto 2024-09-27 um 09 44 26](https://github.com/user-attachments/assets/33c8efab-4c74-4b6d-b100-40f005cccb60)

### Expected Behaviour

Vertical align should be centered

### Browser version

None

**Comment by nmerget** [comment]
@annsch which verison do you use?

The current [main](https://db-ui.github.io/mono/review/main/components/feedback/badge/overview) should work:

![image](https://github.com/user-attachments/assets/6c8c5f0b-d9ce-4ba2-8c48-92fdf2e2e553)
