### ISSUE TITLE
Migration script fails (0.3.X -> 0.4.X)

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#3259]
### Which generators are impacted?

- [x] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Following the migration guide described here: https://github.com/db-ui/mono/blob/main/docs/migration/v0.3.x-to-v0.4.x.md
I get the following error:
````
error: required option '-t, --type [types...]' not specified
````

### Expected Behaviour

Migration without error

### Browser version

None

**Comment by nmerget** [comment]
https://github.com/db-ui/mono/blob/main/docs/migration/v0.2.x-to-v0.3.x.md should be updated as well

**Comment by mfranzke** [comment]
> https://github.com/db-ui/mono/blob/main/docs/migration/v0.2.x-to-v0.3.x.md should be updated as well

@nmerget, ready for review: https://github.com/db-ui/mono/issues/3260

**Comment by nmerget** [comment]
closed by https://github.com/db-ui/mono/issues/3260
