### ISSUE TITLE
Discussion: should Patternlab always redirect to the latest version?

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#3290]
Currently, the url https://db-ui.github.io/mono always redirects to the latest version that is released. In case you want to copy this URL and send it to e.g. a colleague, the redirect leads to a new URL in form of https://db-ui.github.io/mono/version[X.XX]. This could lead to cases that you don't watch the latest version without knowing it.

**Comment by mfranzke** [comment]
speaking in solutions, you're suggesting not to do the redirect but to display the latest released version (which doesn't equal to `main`) when requesting https://db-ui.github.io/mono ? I even also had the same idea and that for would support this !

**Comment by leape** [comment]
that sounds totally useful - has also “annoyed” me several times
➕1️⃣
