### ISSUE TITLE
Default slots not rendered due to vue version conflict

### ISSUE THREAD

**Issue by schneisn** [db-ui/mono#3299]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Our project has a dependency to vue version 3.5.8. Mono has a dependency to vue version 3.5.11.

The conflicting vue versions resulted in default slots not being rendered and the error
`TypeError: Cannot read properties of null (reading 'ce')    at renderSlot`

The same issue is described here: https://stackoverflow.com/questions/72036673/typeerror-cannot-read-properties-of-null-reading-isce-custom-component-li

A possible solution could be to externalize the vue dependency in mono to prevent shipping it and having the vue dependency twice in a project.
See https://vite.dev/guide/build.html#library-mode

### Expected Behaviour

No error occurs.

### Browser version

None

**Comment by mfranzke** [comment]
we'll investigate whether this dependency could actually get moved to be a `devDependency`.
