### ISSUE TITLE
Bessere Trennung der Validierung für positive und negative Validierung von Input Fields

### ISSUE THREAD

**Issue by estherux** [db-ui/mono#3301]
### The problem

Die Entwicklerkollegen hatten Probleme die Feldvalidierung nur für den negativ Fall einzustellen und die positive Darstellung (alles grün + Helfertext) zu "unterdrücken". In unserem Fall bei RiFF brauchen wir die positive Darstellung NICHT. 

Wir haben die Feldvalidierung erstmal komplett ausgestellt und nehmen erstmal nur den Browser Standard z. B. für Pflichtfelder und zeigen nach der Validierung durch einen Button eine Fehlermeldung an. 

### The solution

Mit DB DS DEVs zu klären, ob man das Verhalten der Felder besser entkoppeln kann. Gerne Feedback geben :-) 

### Examples

Aktuelle Lösung für das Pflichtfeld: 
![image](https://github.com/user-attachments/assets/29ac8a49-918c-4e02-847d-856a7a8bf286)

**Comment by nmerget** [comment]
Same as https://github.com/db-ui/mono/issues/3096

**Comment by mfranzke** [comment]
duplicate of https://github.com/db-ui/mono/issues/3096
