### ISSUE TITLE
refactor: Web Component `css` file within template

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#3327]
@nmerget you've removed all `*-web-component.scss` files, but the style URL still seems to be included within the template, isn't it? https://github.com/db-ui/mono/blob/main/packages/components/scripts/post-build/web-components.ts#L98

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/3174#discussion_r1799340360_

**Comment by nmerget** [comment]
Removed the file completly
