### ISSUE TITLE
refactor: questionable selectors

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#3329]
These new selectors additions seem to be redundant to me:
https://github.com/db-ui/mono/pull/3174/files#diff-7698a9195c9745dccb6025bba45cc42cd2617d6e31cc6f7f54a260036c9b5eeeL33-R59

_Originally posted by @mfranzke in https://github.com/db-ui/mono/pull/3174#discussion_r1805922431_

**Comment by nmerget** [comment]
answered in PR
