### ISSUE TITLE
Typo in Link of NPM Landing Page

### ISSUE THREAD

**Issue by laberning** [db-ui/mono#3350]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Go to the Repo page: https://www.npmjs.com/package/@db-ui/components and click the link "Getting started"

### Expected Behaviour

I would expect the link to open the page: https://github.com/db-ui/mono/blob/main/packages/components/docs/getting-started.md, instead it tries to open  the non existent page https://github.com/db-ui/mono/tree/main/packages/components/docs/getting-stated.md

### Browser version

None

### Add any other context about the problem here.

Minor typo in the link ("r" is missing)

**Comment by mfranzke** [comment]
@laberning great catch, thanks a lot !
