### ISSUE TITLE
Add possibility to add drawer header

### ISSUE THREAD

**Issue by mk-94** [db-ui/mono#3359]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [X] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

For the drawer there is the possibility to set a header in plain html. This is not possible in Angular, React and Vue.js.

### Expected Behaviour

It is also possible to set a header in the SPA frameworks.

### Browser version

None

### Add any other context about the problem here.

Perhaps only the documentation is missing.
https://github.com/db-ui/mono/tree/main/packages/components/src/components/drawer/docs

**Comment by nmerget** [comment]
Thanks for the feedback. You are right the documentation was missing. I added it [here](https://github.com/db-ui/mono/pull/3398) :)
