### ISSUE TITLE
Hover recognition is slow / unreliable for menu dropdowns

### ISSUE THREAD

**Issue by flipswitchingmonkey** [db-ui/mono#3366]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

See attached video from https://db-ui.github.io/mono/review/main/foundations/icons/overview

Hover events are not recognized (or handled) correctly when moving over menu entries, in particular when moving slowly. This leads to sometimes chasing around with the mouse to reach a particular sub menu.

https://github.com/user-attachments/assets/0f51111d-4328-4ae3-ad87-d829e9d2a603

### Expected Behaviour

Menus and submenus should immediately show up during hover event, and be snappy about it

### Browser version

None

**Comment by mfranzke** [comment]
@flipswitchingmonkey thanks a lot for your feedback. Actually there's some implementation to ensure that the navigation keeps open even if someone is acting too fast on this navigation. We'll check on further optimizations for this.
