### ISSUE TITLE
Select: Icon size → md (24px) instead of sm (20px)

### ISSUE THREAD

**Issue by leape** [db-ui/mono#3367]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

symbol (Leading and last) should be analog to Input
db-base-icon-font-size-md
instead of
db-base-icon-font-size-sm

also needs to be fixed in the design:
https://github.com/db-ui/design-feedback/issues/138

### Expected Behaviour

see above

### Screenshots

Select
![image](https://github.com/user-attachments/assets/cf5a1824-5792-4435-8ac8-aeb04eb8401d)

Input
![image](https://github.com/user-attachments/assets/ce1e7e48-9d81-4086-a2a2-1cc1902fd243)

### Browser version

None

**Comment by mfranzke** [comment]
The result of this optimization will be deployed https://db-ui.github.io/mono/review/3367-select-leading-icon-size-md-24px-instead-of-sm-20px in approx. 10 minutes.

**Comment by mfranzke** [comment]
we're fixing this in figma.
