### ISSUE TITLE
Add stylelint rule for logical margins and paddings

### ISSUE THREAD

**Issue by nmerget** [db-ui/mono#374]
Like [`-inline`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block) and [`-inline`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline) instead of `-top`, `-bottom`, `-left`, `-right`

**Comment by mfranzke** [comment]
Like [`-inline`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block) and [`-inline`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline) instead of `-top`, `-bottom`, `-left`, `-right`
