### ISSUE TITLE
dependabot still wants to update to major versions

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#455]
[dependabot currently wants to update `@angular/platform-browser-dynamic` (and two others) to a new major version](https://github.com/db-ui/mono/pull/454/commits/015bfe66a98ab426acb1e800404bbd6f517afff9) within the `showcases/angular-lts-showcase/package.json` file, which we would have expected to ignore through the [`ignore` setting within the dependabot config file](https://github.com/db-ui/mono/blob/main/.github/dependabot.yml#L44).

**Comment by nmerget** [comment]
Should be fixed by moving some showcases to https://github.com/db-ui/examples
