### ISSUE TITLE
Evaluate GitHub Blocks

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#486]
Evaluate to use GitHub blocks for creating more enhanced documentation within the repo itself:
https://blocks.githubnext.com/

**Comment by nmerget** [comment]
> With regards to GitHub Blocks, [blocks.githubnext.com](https://blocks.githubnext.com/) will no longer work once the technical preview concludes and we will not make Blocks into a full GitHub product. Blocks was an exciting experiment and thanks to your feedback, we learned a lot about how we might add extensibility to GitHub.com. We expect GitHub will continue to explore this capability in the future, but for now we’re focusing our efforts on other areas.

https://gist.github.com/idan/325676d192b32f169b032fde2d866c2c#github-next--technical-preview-sunsets

**Comment by mfranzke** [comment]
> > With regards to GitHub Blocks, [blocks.githubnext.com](https://blocks.githubnext.com/) will no longer work once the technical preview concludes and we will not make Blocks into a full GitHub product. Blocks was an exciting experiment and thanks to your feedback, we learned a lot about how we might add extensibility to GitHub.com. We expect GitHub will continue to explore this capability in the future, but for now we’re focusing our efforts on other areas.
> 
> https://gist.github.com/idan/325676d192b32f169b032fde2d866c2c#github-next--technical-preview-sunsets

schade 🍫

**Comment by mfranzke** [comment]
you're always searching for challenges, aren't you?
https://gist.github.com/idan/325676d192b32f169b032fde2d866c2c?permalink_comment_id=4825783#gistcomment-4825783
