### ISSUE TITLE
fix: style icon font-familiy without using pseudo elements

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#497]
To make DBIcon work with Web Components we have to ensure to change icons font-family in parent component without using pseudo elements like :before or :after.
Afterwards we should refactor all components that use DBIcon

**Comment by mfranzke** [comment]
> To make DBIcon work with Web Components we have to ensure to change icons font-family in parent component without using pseudo elements like :before or :after. Afterwards we should refactor all components that use DBIcon

Besides that I think that it would only make our components more resilient not to provide code that interferes this way within other components, but only the outer wrapper (in this case `db-icon` or `.db-icon`), and to provide an explicit API in the form of CSS Custom Properties.
