### ISSUE TITLE
refactor: cursor pointer for clickable elements/components

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#498]
As discussed before, we like to ensure that every clickable element has cursor: pointer (buttons, accordion, etc.) 
- [ ] adr must be updated 
- [x] global solution (init.scss or placeholder, ...)
- [x] get an explicit scope of these elements by creative colleagues, our suggestions:
  - [x] `input`
  - [x] `label`
  - [x] `textarea`
  - [x] `button`
  - [x] `summary`

**Comment by mfranzke** [comment]
Defining the exact scope of "clickable elements" is key on this topic, as e.g. an `input` is clickable also as well as a `label`.
