### ISSUE TITLE
Don't we need radio in this list and files as well ?

### ISSUE THREAD

**Issue by mfranzke** [db-ui/mono#876]
https://github.com/db-ui/mono/blob/22c026bd73a8b2736638af6d07bc50b17cfffbbe/showcases/patternhub/components/component-parser/data.ts#L8-L26

https://github.com/db-ui/mono/blob/0e97fb78475d348307644386ffe39d5a68c51464/showcases/patternhub/components/component-parser/index.tsx#L5-L15

**Comment by nmerget** [comment]
Yes :)

Guess it was not generated when we started with radio

**Comment by mfranzke** [comment]
should I take over this one, or do you want to?

**Comment by nmerget** [comment]
Go for it, thx 👍
