### ISSUE TITLE
Refactor: Floating Label

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#908]
- [ ] same solution for Textarea, Input and Select
- [ ] use transform animation for all

**Comment by mfranzke** [comment]
most likely there are still some declarations that need to be specific, as only `textarea` and `input` could behave uniquely (by `:placeholder-shown`) whereas `select` would need some different construct:
https://github.com/db-ui/core/blob/main/source/_patterns/01-elements/select/select.scss#L42-L48
