### ISSUE TITLE
Feat: styling :autofill & caret-color with DB Colors

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#909]
- https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill
- https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color (we had this colored in red with Guidelines 2)

We should discuss this with our design colleagues first (which color should we use)

**Comment by mfranzke** [comment]
> [Autofill](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill) in chrome is set with !important so we cannot overwrite it with our `informational` color which would be the best I guess. But we can change the caret-color :)

I'm not sure, if I'm missing something here, but even `:autofill` worked fine within the MDN example on my Google Chrome 120 test:
<img width="350" alt="image" src="https://github.com/db-ui/mono/assets/787658/ce7e7e01-3a7d-45e8-a388-6fd20feec881">
